#!/usr/bin/env python3
"""Import FFXI minimap pages from an installed client or Pivot overlay.

The generated PNGs and Lua catalog are local deployment artifacts. They are
intentionally gitignored because the source artwork belongs to the game
installation and is not redistributed by this repository.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

from PIL import Image, ImageChops

from generate_vanilla_map import decode


PAGE_PATTERN = re.compile(rb"m_(\d{3})_(\d{2})")


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "ffxi_root",
        type=Path,
        help="FINAL FANTASY XI directory containing ROM folders",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("assets/vanilla"),
        help="generated PNG directory",
    )
    parser.add_argument(
        "--catalog",
        type=Path,
        default=Path("ashitaminimap_vanilla_maps.lua"),
        help="generated runtime Lua catalog",
    )
    parser.add_argument(
        "--asset-prefix",
        default="assets/vanilla",
        help="runtime path prefix written into the Lua catalog",
    )
    parser.add_argument(
        "--source-label",
        default="locally installed FFXI DAT files",
        help="non-sensitive source description written into the catalog",
    )
    return parser.parse_args()


def rom_rank(root: Path, path: Path) -> tuple[int, int]:
    relative = path.relative_to(root)
    directory = relative.parts[0]
    if directory.upper() == "ROM":
        rom_number = 0
    else:
        match = re.fullmatch(r"ROM(\d+)", directory, re.IGNORECASE)
        rom_number = int(match.group(1)) if match else -1
    try:
        file_number = int(path.stem)
    except ValueError:
        file_number = -1
    return rom_number, file_number


def page_identity(path: Path) -> tuple[int, int] | None:
    with path.open("rb") as source:
        header = source.read(0x100)
    match = PAGE_PATTERN.search(header)
    if match is None:
        return None
    zone_id, page_id = (int(value) for value in match.groups())
    if zone_id <= 0:
        return None
    return zone_id, page_id


def is_dxt3(path: Path) -> bool:
    with path.open("rb") as source:
        header = source.read(0x100)
    type_offset = header.find(b"3TXD")
    header_offset = type_offset - 0x39
    return (
        type_offset >= 0
        and header_offset >= 0
        and header[header_offset] in (0xA1, 0xB1)
    )


def select_candidates(root: Path) -> tuple[dict[tuple[int, int], Path], int]:
    grouped: dict[tuple[int, int], list[Path]] = defaultdict(list)
    for path in root.rglob("*.DAT"):
        identity = page_identity(path)
        if identity is not None:
            grouped[identity].append(path)

    selected: dict[tuple[int, int], Path] = {}
    duplicate_count = 0
    for identity, paths in grouped.items():
        if len(paths) > 1:
            duplicate_count += len(paths) - 1
        # Later ROM directories contain replacement/current map pages. Prefer
        # the compressed page when both a legacy palette and DXT3 copy exist.
        selected[identity] = max(
            paths,
            key=lambda path: (is_dxt3(path), *rom_rank(root, path)),
        )
    return selected, duplicate_count


def export_page(source: Path, destination: Path) -> None:
    image = decode(source).convert("RGBA")
    if not is_dxt3(source):
        # The legacy indexed layout stores the A-D strip after E-O.
        image = ImageChops.offset(image, 146, 0)
    image.putalpha(Image.new("L", image.size, 255))
    destination.parent.mkdir(parents=True, exist_ok=True)
    image.save(destination, "PNG", optimize=True)


def lua_catalog(
    pages: dict[int, dict[int, str]],
    duplicate_count: int,
    source_label: str,
) -> str:
    lines = [
        "-- Generated by tools/import_vanilla_maps.py.",
        f"-- Source: {source_label}; do not redistribute.",
        f"-- Discovered {sum(len(value) for value in pages.values())} pages "
        f"across {len(pages)} zones; resolved {duplicate_count} duplicate candidates.",
        "return {",
    ]
    for zone_id in sorted(pages):
        page_ids = sorted(pages[zone_id])
        default_page = 0 if 0 in pages[zone_id] else (
            1 if 1 in pages[zone_id] else page_ids[0]
        )
        lines.append(f"    [{zone_id}] = {{")
        lines.append(f"        default_page = {default_page},")
        lines.append("        pages = {")
        for page_id in page_ids:
            lines.append(
                f"            [{page_id}] = '{pages[zone_id][page_id]}',"
            )
        lines.extend(("        },", "    },"))
    lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> None:
    args = arguments()
    root = args.ffxi_root.resolve()
    if not root.is_dir():
        raise SystemExit(f"FFXI root does not exist: {root}")

    selected, duplicate_count = select_candidates(root)
    pages: dict[int, dict[int, str]] = defaultdict(dict)
    for index, ((zone_id, page_id), source) in enumerate(
        sorted(selected.items()), start=1
    ):
        filename = f"{zone_id:03d}_{page_id:02d}.png"
        destination = args.output / filename
        export_page(source, destination)
        pages[zone_id][page_id] = (
            f"{args.asset_prefix.rstrip('/')}/{filename}"
        )
        if index % 50 == 0:
            print(f"imported {index}/{len(selected)} pages")

    args.catalog.parent.mkdir(parents=True, exist_ok=True)
    args.catalog.write_text(
        lua_catalog(pages, duplicate_count, args.source_label),
        encoding="utf-8",
        newline="\n",
    )
    print(
        f"wrote {len(selected)} pages across {len(pages)} zones; "
        f"catalog: {args.catalog}"
    )


if __name__ == "__main__":
    main()
